const LOGIN_CODES = {
  DB_ERROR: 'DB_ERROR',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ERROR_PASSWORD: 'ERROR_PASSWORD',
  AUTH_SUCCESS: 'AUTH_SUCCESS',
  ERROR_USER_EXISTS: 'ERROR_USER_EXISTS'
}

const PLANES_CODES = {
  NOT_FOUND: 'NOT_FOUND',
  GET_ALL: 'GET_ALL'
}

export {
  LOGIN_CODES,
  PLANES_CODES
}
